# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-03 16:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapplication', '0002_students_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 3, 22, 5, 16, 273000)),
        ),
    ]
