# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-04 15:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapplication', '0003_auto_20180103_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='noofdays',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='students',
            name='rollno',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='students',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 4, 21, 16, 23, 836000)),
        ),
    ]
