# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-04 15:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapplication', '0004_auto_20180104_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='noofdays',
        ),
        migrations.RemoveField(
            model_name='students',
            name='rollno',
        ),
        migrations.AlterField(
            model_name='students',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 4, 21, 23, 38, 47000)),
        ),
    ]
