# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-04 16:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapplication', '0005_auto_20180104_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 4, 21, 31, 8, 282000)),
        ),
    ]
