# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-04 16:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapplication', '0006_auto_20180104_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='rollno',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='students',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 4, 21, 34, 54, 393000)),
        ),
    ]
