# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-08 17:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapplication', '0009_auto_20180104_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=8, unique=True)),
                ('password', models.CharField(max_length=8)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='students',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 8, 22, 52, 30, 39000)),
        ),
        migrations.AlterField(
            model_name='students',
            name='rollno',
            field=models.CharField(max_length=8),
        ),
    ]
