# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-08 18:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapplication', '0014_auto_20180108_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='students',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 8, 23, 50, 19, 374000)),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='rollno',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
