# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-23 17:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapplication', '0019_auto_20180108_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_password',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='students',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 23, 22, 37, 58, 710919)),
        ),
    ]
