# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-23 17:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapplication', '0021_auto_20180123_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 23, 22, 47, 22, 395160)),
        ),
    ]
