# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 19:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapplication', '0025_auto_20180125_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 25, 0, 31, 21, 536786)),
        ),
    ]
