# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-25 15:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapplication', '0026_auto_20180125_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='email',
        ),
        migrations.RemoveField(
            model_name='students',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='students',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='students',
            name='rollno',
        ),
        migrations.AlterField(
            model_name='students',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 25, 20, 36, 0, 997137)),
        ),
    ]
