# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-25 15:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapplication', '0028_auto_20180125_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='apply_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leaveapplication.user'),
        ),
        migrations.AlterField(
            model_name='students',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 25, 20, 57, 0, 860428)),
        ),
    ]
