# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-26 10:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapplication', '0036_auto_20180125_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='date',
        ),
        migrations.AddField(
            model_name='students',
            name='from_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 26, 15, 32, 58, 857620)),
        ),
        migrations.AddField(
            model_name='students',
            name='status',
            field=models.CharField(default='Submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='students',
            name='to_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 26, 15, 32, 58, 857620)),
        ),
        migrations.AlterField(
            model_name='students',
            name='reason',
            field=models.CharField(choices=[('personal', 'PERSONAL'), ('sick', 'SICK'), ('od', 'OD'), ('studyleave', 'STUDY LEAVE')], max_length=100),
        ),
    ]
