# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-27 17:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapplication', '0039_auto_20180127_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='apply_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leaveapplication.user'),
        ),
        migrations.AlterField(
            model_name='students',
            name='from_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 27, 22, 30, 12, 408745)),
        ),
        migrations.AlterField(
            model_name='students',
            name='to_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 27, 22, 30, 12, 408745)),
        ),
    ]
