# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 07:38
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapplication', '0041_auto_20180127_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='applied_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 28, 13, 8, 44, 950058)),
        ),
        migrations.AddField(
            model_name='students',
            name='approved_date',
            field=models.CharField(default='Waiting', max_length=30),
        ),
        migrations.AlterField(
            model_name='students',
            name='apply_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='students',
            name='from_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 28, 13, 8, 44, 950058)),
        ),
        migrations.AlterField(
            model_name='students',
            name='to_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 28, 13, 8, 44, 950058)),
        ),
    ]
