# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 07:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapplication', '0042_auto_20180128_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='applied_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 28, 13, 12, 53, 676284)),
        ),
        migrations.AlterField(
            model_name='students',
            name='approved_date',
            field=models.CharField(default='Waiting', max_length=19),
        ),
        migrations.AlterField(
            model_name='students',
            name='from_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 28, 13, 12, 53, 676284)),
        ),
        migrations.AlterField(
            model_name='students',
            name='to_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 28, 13, 12, 53, 676284)),
        ),
    ]
